#KhanhNguyen9872
name: Ubuntu-22.04

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    name: Image Build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install VNC Ubuntu-22.04
        run: |
          printf "\n Preparing....\n\n"
          sudo apt update -y > /dev/null 2>&1
          sudo apt install curl openssl -y > /dev/null 2>&1
          curl -L --max-redirs 15 --progress-bar "https://raw.githubusercontent.com/usertest9872/ubuntu_on_github/main/install.sh" --output install.sh > /dev/null 2>&1
          bash ./install.sh
